name: Install Helm
description: Installs Helm on win64 runner
inputs:
  version:
    description: 'The Helm version to install. Specify "latest" to install the latest version.'
    required: false
    default: 'latest'
runs:
  using: composite
  steps:
    - name: Set up Git environment
      uses: actions/checkout@v2

    - name: Get Helm latest version
      shell: cmd
      run: |
        set "VERSION=%{{ inputs.version }}%"

        if "%VERSION%"=="latest" (
          for /f "usebackq tokens=3" %%i in (`curl -sL https://api.github.com/repos/helm/helm/releases/latest ^| findstr /C:"tag_name"`) do (
            set "VERSION=%%~i"
          )
        )
        echo %{{ inputs.version }}%
        echo %VERSION%




