name: Install Helm
description: Installs Helm on win64 runner
inputs:
  version:
    description: 'The Helm version to install. Specify "latest" to install the latest version.'
    required: false
    default: 'latest'
runs:
  using: composite
  steps:
    - name: Set up Git environment
      uses: actions/checkout@v2

    - name: Get Helm latest version
      shell: cmd
      run: |
        if '${{ inputs.version }}' == 'latest' (
        set %LATEST_VERSION%=v3.12.0
        echo %LATEST_VERIOSN% >> %GITHUB_ENV%
        echo %GITHUB_ENV%
        set
        ) else (
        set %LATEST_VERSION%=v${{ inputs.version }}
        echo %LATEST_VERIOSN% >> %GITHUB_ENV%
        echo %GITHUB_ENV  
        set     
        )
        set URL=https://get.helm.sh/helm-%LATEST_VERIOSN%-windows-amd64.zip
        echo %URL%
        
