name: Install Helm
description: Installs Helm on win64 runner
inputs:
  version:
    description: 'The Helm version to install. Specify "latest" to install the latest version.'
    required: false
    default: 'latest'
runs:
  using: composite
  steps:
    - name: Set up Git environment
      uses: actions/checkout@v2

    - name: Get Helm latest version
      shell: cmd
      run: |
        if '${{ inputs.version }}' == 'latest' (
          for /f "delims=" %%L in ('powershell.exe -Command "(Invoke-WebRequest -Uri 'https://api.github.com/repos/helm/helm/releases/latest' -UseBasicParsing).Content | ConvertFrom-Json | Select-Object -ExpandProperty tag_name"') do set LATEST_VERSION=%%L
          set URL=https://get.helm.sh/helm-%LATEST_VERSION%-windows-amd64.zip
        ) else (
          set URL=https://get.helm.sh/helm-${{ inputs.version }}-windows-amd64.zip
        )
        echo "The helm version that will be installed is" %LATEST_VERSION%$ {{inputs.version}}
        
