on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job set up helm v2
    steps:
      - uses: actions/checkout@v3
      - name: installing helm
        uses: ./windows_cmd/

      - name: validation
        shell: cmd
        run: |
          helm version --short
